### ISSUE TITLE
Data dashboard - missing image

### ISSUE THREAD

**Issue by axdanbol** [x-atlas-consortia/hra-dashboard-data#1]
The following line needs to be an image not a json. I tried to find the image in https://github.com/x-atlas-consortia/hra-dashboard-data/tree/main/data/data but it is missing the image for 'hra-growth'
https://github.com/x-atlas-consortia/hra-dashboard-data/blob/43dbbb2b82ea988459e1a15aeb79868ab3bb0dd3/data/dashboards/data.yaml#L58

**Comment by bherr2** [comment]
Yes, sorry, that was misclassified. It is a vega-lite visualization. I've updated the data.yaml to correctly identify it in main.
