### ISSUE TITLE
Fix zoom angle and center for Sankey

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-dashboard-data#3]
Any chance we can set the default zoom level to fit the screen? 

![image](https://github.com/x-atlas-consortia/hra-dashboard-data/assets/22821046/2a3846b4-5450-4464-8c0c-64be89c95f99)

-> 

![image](https://github.com/x-atlas-consortia/hra-dashboard-data/assets/22821046/c705271b-abb3-4a8e-8dc5-9f15b080c513)

**Comment by bherr2** [comment]
We'll need to download and tweak the generated html from your sankey html to do that. Something we can work on early next week, but there is not a simple solution.

**Comment by andreasbueckle** [comment]
Sounds good! The HTML lives at https://github.com/cns-iu/hra-cell-type-populations-supporting-information/blob/main/docs/sankey_atlas.html

**Comment by andreasbueckle** [comment]
No cycles, happy to leave this one to you and your team!

**Comment by bherr2** [comment]
Ok, I downloaded and modified it to properly fit the window! Will need to make another fix on dashboards to remove the outer border.
